#!/bin/bash
echo "=== Cloudflare Tunnel Setup for Backend Server ==="
echo ""
echo "This script should be run ON THE BACKEND SERVER (168.119.241.59)"
echo "NOT on your local Mac!"
echo ""
echo "Steps to set up tunnel on backend server:"
echo ""
echo "1. SSH into backend server:"
echo "   ssh root@168.119.241.59"
echo ""
echo "2. On the backend server, run:"
echo "   curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared"
echo "   chmod +x /usr/local/bin/cloudflared"
echo ""
echo "3. Login to Cloudflare (on backend server):"
echo "   cloudflared tunnel login"
echo ""
echo "4. Create named tunnel (on backend server):"
echo "   cloudflared tunnel create audio-city-backend"
echo ""
echo "5. Run tunnel pointing to localhost:3002 (on backend server):"
echo "   cloudflared tunnel --url http://localhost:3002"
echo ""
echo "6. Get the tunnel URL from output, then set in Cloudflare Workers:"
echo "   Workers & Pages → audio-city-api-proxy → Settings → Variables"
echo "   Set BACKEND_URL = https://[tunnel-url].cfargotunnel.com"
echo ""
echo "=== For Testing (Temporary) ==="
echo "You can use the temporary tunnel URL for testing:"
echo "https://define-monroe-doll-duties.trycloudflare.com"
echo ""
echo "But this is temporary and will expire. Use a named tunnel for production."
