#!/bin/bash
echo "=========================================="
echo "Cloudflare Tunnel Setup for Backend Server"
echo "=========================================="
echo ""
echo "This script will help you set up the tunnel on your backend server."
echo "Run these commands ON THE BACKEND SERVER (168.119.241.59), not on your Mac!"
echo ""
echo "Step 1: SSH to backend server"
echo "  ssh root@168.119.241.59"
echo ""
echo "Step 2: Install cloudflared"
echo "  curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared"
echo "  chmod +x /usr/local/bin/cloudflared"
echo ""
echo "Step 3: Login to Cloudflare"
echo "  cloudflared tunnel login"
echo "  (This will open a browser - authenticate with your Cloudflare account)"
echo ""
echo "Step 4: Create named tunnel"
echo "  cloudflared tunnel create audio-city-backend"
echo ""
echo "Step 5: Run tunnel pointing to your backend"
echo "  cloudflared tunnel --url http://localhost:3002"
echo ""
echo "Step 6: Get the tunnel URL from output"
echo "  (Look for: https://[tunnel-id].cfargotunnel.com)"
echo ""
echo "Step 7: Set in Cloudflare Workers"
echo "  1. Go to: https://dash.cloudflare.com"
echo "  2. Workers & Pages → audio-city-api-proxy"
echo "  3. Settings → Variables"
echo "  4. Set BACKEND_URL = https://[tunnel-url].cfargotunnel.com"
echo "  5. Save"
echo ""
echo "Step 8: Keep tunnel running (use PM2)"
echo "  npm install -g pm2"
echo "  pm2 start cloudflared --name tunnel -- tunnel --url http://localhost:3002"
echo "  pm2 save"
echo "  pm2 startup"
echo ""
echo "=========================================="
echo "After setup:"
echo "✅ Tunnel runs on backend server 24/7"
echo "✅ Site works even when your Mac is off"
echo "✅ No need to keep terminal open"
echo "=========================================="
